spring.application.name=hospital-management-service

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital-management-service
spring.datasource.username=mayankgupta
spring.datasource.password=qwertyuiop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
